### ISSUE TITLE
cannot import miniconfig's objects

### ISSUE THREAD

**Issue by TakesxiSximada** [podhmo/miniconfig#1]
Maybe, specified argument in find_packages is mistaken.
https://github.com/podhmo/miniconfig/blob/3b969df144eb2c84245983350863486e7d5edc4e/setup.py#L61

**Comment by podhmo** [comment]
wow

**Comment by podhmo** [comment]
thx. merged and released.

**Comment by TakesxiSximada** [comment]
yay
